version: '3.3'                                     
services:                                            
  web:                                      
    image: bprawit/odoo_thai:10.0
    command: odoo --db_host=db --db_port=5432 --db_user=${POSTGRES_USER} --db_password=${POSTGRES_PASSWORD}
    depends_on:
      - db
    # Ports section, 8069 is main website, 8072 is longpulling.
    ports:
      - "8069:8069"
      - "8072:8072"
    # Uncomment below row if you want this service auto start when start docker
    # restart: always                                  
    logging:                                         
      driver: "json-file"                            
      options:                                       
        max-size: "50m"
        max-file: "10"
    volumes:                                         
      - ./odoo-web-data:/var/lib/odoo                  
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./backup:/backup
  db:
    image: postgres:9.4
    # Uncomment ports section if you don't want to directly access the database.
    ports:                                           
      - "5432:5432"
    # Uncomment below row if you want this service auto start when start docker
    # restart: always
    # Logging section prevents your hard disk full, 
    # Especially when you use this image in the cloud such as Digitalocean, etc.
    logging:                                         
      driver: "json-file"                            
      options:                                       
        max-size: "50m"                              
        max-file: "10"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
volumes:
  db-data: